version: 2.1

jobs:
  build-test-deploy:
    machine: true
    working_directory: "~/docker-cache"
    environment:
      APP_NAME: aws
      APP_VERSION: 1.16.26
    steps:
      - run:
          name: Docker version
          command: |
            docker info
            docker --version
      - restore_cache:
          key: docker-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build image
          command: |
            docker build -t cgswong/${APP_NAME}:${APP_VERSION} .
      - run:
          name: Test version
          command: |
            docker run cgswong/${APP_NAME}:${APP_VERSION} aws --version
      - save_cache:
          key: docker-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - "~/docker-cache"
      - deploy:
          command: |
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            docker push cgswong/${APP_NAME}:${APP_VERSION}

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-test-deploy
