version: 2
jobs:
  build:
    machine: true
    working_directory: "~/docker-cache"
    steps:
      - checkout
      - run:
        name: Docker version
        command: 'docker info'
      - restore_cache:
        key: docker-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
        name: Build image
        command: 'docker build -t cgswong/aws:latest'
      - save_cache:
        key: docker-cache-{{ .Environment.CIRCLE_SHA1 }}
        paths:
          - "~/docker-cache"
  test:
    steps:
      - checkout
      - run:
        name: Test version
        command: 'docker run cgswong/aws:latest aws --version'

  deploy:
    machine:
      enabled: true
    working_directory: "~/docker-cache"
    docker_store:
      command: $DEPLOY

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
        filters:
          branches:
            only: master
      - deploy
